services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - .:/app
      - /app/static_compiled  # Preserve built static files from Docker image
    ports:
      - "8000:8000"
    environment:
      DJANGO_SETTINGS_MODULE: app.settings.dev
      DJANGO_ALLOWED_HOSTS: ${DJANGO_ALLOWED_HOSTS}
      DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY}
      WAGTAIL_SITE_NAME: ${WAGTAIL_SITE_NAME}
      WAGTAILADMIN_BASE_URL: ${WAGTAILADMIN_BASE_URL}
    command: tail -f /dev/null

  # Email testing utility — catches all outgoing mail, preview at http://localhost:8025
  mailhog:
    image: mailhog/mailhog
    platform: linux/amd64
    logging:
      driver: 'none'
    ports:
      - 1025:1025  # smtp server
      - 8025:8025  # web ui
